version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: local
    networks:
      - repo-info-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8001:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: local
      ME_CONFIG_MONGODB_URL: mongodb://root:local@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - repo-info-network

  app:
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: debug
      MONGODB_CONNECTION_URI: mongodb://root:local@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - repo-info-network
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules

volumes:
  nodemodules:

networks:
  repo-info-network:
    driver: bridge
